# Site settings
title: Musab Ismail
description: Musab Ismail Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Musab Ismail 
user_description: I'm a Software Engineer from Argentina, always searching for the next challenge; no task is too scary nor too difficult. Lately I have been immersed in world of Giving Circles working with Grapevine, a California based startup trying to improve the world through collaborative giving. I'm the first engineer they hired to work on the platform.
user_title: IT Security | SOC Analyst | PenTester
email: musabismail12@gmail.com
# twitter_username: lorem_ipsum
instagram_username: wdamkzool
facebook_username: wdamkzool
linkedin_username: musabz1
github_username:  wdamkzool
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
